### ISSUE TITLE
Add duration member

### ISSUE THREAD

**Issue by annevk** [whatwg/notifications#11]
To allow for transient notifications.

Also make the "notification center" concept more explicit, while allowing for implementation to have various strategies around it.

**Comment by sid5491** [comment]
As of now the default time of visibility for my push message on chrome browser is 19 seconds which is too low, But Other push services like OneSignal, Pushcrew, Let Reach are having visibility time of upto 3 minutes for there messages. How can i do that, Need some help with this please

**Comment by mvano** [comment]
There is currently no way to specify the duration on a non-persistent notification, that's what this issue is about. Currently all implementations use a default value.

However, as suggested in [1] you can try setting a timeout.

[1] https://lists.w3.org/Archives/Public/public-whatwg-archive/2014Apr/0062.html

**Comment by annevk** [comment]
Closing this due to lack of interest.
