### ISSUE TITLE
Deprecating non-persistent notifications

### ISSUE THREAD

**Issue by beverloo** [whatwg/notifications#26]
The specification currently defines two types of notifications, persistent and non-persistent ones, identified by whether they're associated with a Service Worker or not.

If we were to design the Notification API today, would we still have this distinction? I don't think we would. 

Reliability of the notifications obviously is the primary motivation behind this, and I don't think I have to repeat any of the other arguments that backed introduction of persistent notifications in the first place.

A number of pieces of functionality of non-persistent notifications have been removed recently, notably the show and close events. What about going taking another jump, and deprecating support for them altogether?

For Chrome for Android, we're ready to ship Service Workers-based notifications, and would very much prefer to not ship non-persistent notifications if we can find a path towards deprecating them.

**Comment by phistuck** [comment]
I do not understand why would you want to deprecate `new Notification(...)` and not implement it on mobile.
If the page is active (the `window` that created the notification is still there, in a background or foreground tab that still has a renderer process), tapping the notification would go to the browser and focus on that tab. If the page is inactive, open a new tab and go to it.
I think this is reasonable. A use case? Remember that a notification usually makes a familiar sound (or vibrates, or both), so - say, I went to a forex or an auction website and I wait for a bid price to reach a certain price and when it is close to it, the site can notify me. I leave the website as a foreground tab and do my non mobile things while I wait (organizing my room, for example). I get a notification, turn on the screen and trade. Same for a background tab. If my phone is not powerful, then the notification will either not show up, or if it showed up during the seconds after which the renderer has gone inactive, tapping the notification will still bring me back to (a newly loaded) page and I can see the current bid price. Ultimately, using notification is a decision of websites, knowing they might be swapped out.

**Comment by beverloo** [comment]
I'm entirely open to non-persistent notifications, but it will take time to flesh out how they work.

We've been talking about it in the team here and agree that something similar to a [Toast-like](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7bjM5V3Nxb09sQms/components_toasts_tabletdesktop2.png) appearance would be workable and nice for mobile. It just hasn't been the priority.

As for your suggestion - we've considered that and there are a whole bunch of timing issues. To name some obvious ones, what if the user taps the notification twice in quick succession? What if there are two tabs open with the same URL? A notification doesn't have to come from a *tab*, it could be a shared or service worker too. Furthermore, the event handler will be gone when we load a new tab, so clicking on a notification about a breaking news article wouldn't actually show you the article.

To give you a though exercise: In what situation provides the Web-current "new Notification()" model benefits over the Service Workers-based showNotification() model?

**Comment by phistuck** [comment]
Having a service worker is somewhat similar to installing a (web) application. Switching to this is like forgetting the (great) ephemeral nature of the web - you do not have to install or permit anything, it just works. It does not affect your system (other than disk space taken by cache and data), it does not slow your system down and it does not eat memory when you close that tab/window.

**Comment by beverloo** [comment]
With all due respect, that makes no sense. Please read up on how Service Workers work: they do not impact ephemerality at all (they work for the _drive-by_ web just as well), they do not continuously run in the background and they're no resource hogs either.

It does require a bit more boilerplate to handle persistent notifications, but that's ~5 lines of JavaScript. Nothing to worry about.

**Comment by phistuck** [comment]
Taking a simple concept and turning it into a complicated one is weird. A desktop notification (on desktop) is a very simple concept that should be preserved, not made more complicated. Service workers are overkill for this simple concept. You would have to start posting messages to your service worker in order to show notifications (unless I understand incorrectly), that is an overkill than just `new Notification("You have a new message.");`.

**Comment by annevk** [comment]
It seems we're keeping non-persistent notifications.

**Comment by vandys** [comment]
> As for your suggestion - we've considered that and there are a whole bunch of timing issues. To name some obvious ones, what if the user taps the notification twice in quick succession? What if there are two tabs open with the same URL? A notification doesn't have to come from a tab, it could be a shared or service worker too. Furthermore, the event handler will be gone when we load a new tab, so clicking on a notification about a breaking news article wouldn't actually show you the article.

I'm a little concerned at this line of argument, because it seems like all of this is addressed
by having a bookmark on one's home screen.  Tap twice (debounce).  Two tabs at URL
(choose one).  Tap as GC clean tabs--serialize.  Either GC wins (no tab, so open one) or
tap wins (tab is current, GC leaves alone).  All of this needs to be addressed for the simple
use case of a bookmark icon (and if it isn't, you should fix your bugs!).

When one studies the state of Service Workers, almost all the documentation one reads
shows their focus on the offline content problem.  That the most compelling way to
use them in this space involves an empty source file feels a bit like having a hammer and
wanting everything to be nails.

Notifications with URL's.  By default, the URL of the page which instantiated the Notification.
Permit explicit.  If you're in a context without a URL, *require* explicit.  Use the semantics
of a home page bookmark when dispatching from URL to tab.
