### ISSUE TITLE
new Notification succeeds even if permission is "denied"

### ISSUE THREAD

**Issue by owencm** [whatwg/notifications#34]
As a developer I think it's strange that calling new Notification without appropriate permission succeeds and returns a notification object as if it was displayed.

I would expect it to throw an error or somehow indicate the call failed.

**Comment by annevk** [comment]
It seems unlikely we can change this. The reasoning was that code creating notifications might not wish to have to deal with permissions.

**Comment by owencm** [comment]
That doesn't make much sense to me. The ability to send notifications is explicitly something a site needs elevated permissions for so it is totally justifiable to expect code that wants to display them to worry about permission state :/.

**Comment by beverloo** [comment]
All current implementations support support `error` and `show` events on the Notification object.
```
var notification = new Notification();
notification.addEventListener('error', function() {
    console.error('The notification could not be displayed.');
});
notification.addEventListener('show', function() {
    console.log('The notification has been displayed.');
});
```

The `show` event has been removed from the specification as the meaning of `new Notification()` changed, but I'm not aware of any implementation that's matching this as of yet.

For backwards compatibility reasons I agree that changing `new Notification()` to throw when there is no permission may be tedious. At the same time, Chrome for Android will throw when constructing the object because non-persistent notifications are not supported (yet), but I'm not aware of any issues in this regard.

**Comment by annevk** [comment]
@owencm you could imagine one part of your code dealing with permissions while another part of your code creates notifications. With the existing design the latter part would not have to care about permissions.

But some of this stems from how the API evolved. If we could make it throw and also get rid of the error event for this case that might be nice...

**Comment by annevk** [comment]
It seems more likely we'd just get rid of non-persistent notifications than that we'd ever change how they work. And getting rid of them also seems unlikely (and not necessarily desirable).
