### ISSUE TITLE
Move permission check to main body of showNotification()

### ISSUE THREAD

**Issue by nikhilm** [whatwg/notifications#42]
Is there a reason step 5.1 has to be in parallel?
"
If permission for notification’s origin is not "granted", reject promise with a TypeError exception, and terminate these substeps.
"
Gecko will be doing the permission check in serial. I don't think that violates anything in the spec, but just wanted to confirm.

**Comment by beverloo** [comment]
Chrome does the check asynchronously. I don't think the difference really matters here.

**Comment by annevk** [comment]
The reason is that the permission might be stored in "chrome" and "content" does not necessarily have synchronous access to "chrome". At some point we should define these concepts of the browser somewhat more coherently so that it's more clear what should be obviously asynchronous and what's legacy synchronous, etc.

**Comment by annevk** [comment]
(You are of course free to perform asynchronous checks synchronously, but it should not be observable.)
