### ISSUE TITLE
"If options’s lang is either a valid BCP 47 lang..."

### ISSUE THREAD

**Issue by sideshowbarker** [whatwg/notifications#46]
https://notifications.spec.whatwg.org/#notifications

> If options’s lang is either a valid BCP 47 language tag or the empty string, set notification’s language to options’s lang, and set it to the empty string otherwise. [LANG]

No UAs that implement Web Notifications currently do any checking at all of the value of the `lang` option given to the Notification constructor—neither for validity nor for the basic microsyntax/datatype of the value. Instead they all just pass the value on as-is such that it becomes the value of the `lang` property of the Notification instance. The only case where the `lang` value given to the constructor will result in the empty string as the value of the `lang` property of an instance is if the empty string for the `lang` option is given to the constructor.

So it seems we’re unlikely to get UAs to implement the existing requirement, and I think at this point we should consider changing this step to simply say:
> Set *notification's* [language]() to *options's* `lang`.

**Comment by annevk** [comment]
Did we try to file bugs on user agents?

**Comment by sideshowbarker** [comment]
> Did we try to file bugs on user agents?

I haven't tried. But I wonder whether we know now when the requirement was originally added and if we still have agreement about the rationale behind it. [Feedback on this from the i18n Core WG](https://lists.w3.org/Archives/Public/public-i18n-core/2015JulSep/0002.html) seems to indicate that in practice they at least don’t place much value on this requirement as currently specified.

Along with that, regarding implementations, I wonder whether we know if UAs already maintain and use data about valid BCP-47 language tags for some other purposes (e.g., requirements in other specs, or for internal purposes).

If UAs aren’t already data about valid BCP-47 language tags, it makes me wonder whether them adding it for just the purpose of this one requirement in this spec is worth the cost/complexity when compared to the current as-implemented UA behavior of just always passing the value on unaltered.

That current UA behavior doesn’t seem to have caused any real problems with Notification behavior for actual users in practice. At least I can't find any browser bug reports of any problems it has caused.

**Comment by sideshowbarker** [comment]
> Feedback on this from the i18n Core WG seems to indicate that in practice they at least don’t place much value on this requirement as currently specified.

oops, the link there should instead be to https://lists.w3.org/Archives/Public/public-i18n-core/2015JulSep/0004.html

**Comment by annevk** [comment]
So CSS has `:lang()`... I guess that doesn't enforce much. HTML's `lang` certainly doesn't enforce anything. Not sure what else there is.

**Comment by sideshowbarker** [comment]
> So CSS has :lang()... I guess that doesn't enforce much. HTML's lang certainly doesn't enforce anything. Not sure what else there is.

As far as the gecko sources go, a quick search turns up https://dxr.mozilla.org/mozilla-central/source/intl/icu/source/common/uloc.cpp#96 (and on further in the rest of that file). I haven’t looked much more in detail at that but I assume it exposes some internal interface that code which implemented the valid-BCP-47 requirement in this spec could hook into.

So if other UAs have similar existing code, maybe the implementation cost of this requirement wouldn’t actually be so high and we should just go ahead and file browser bugs for it.

But as I mentioned earlier I wonder whether we still (or ever did) have agreement that the requirement is a good, actually-useful one (rather than just a relic of what somebody thought was a good idea to add to the spec sometime, way back when).

**Comment by annevk** [comment]
I added this feature based on feedback from the i18n WG I believe. Though perhaps their requirements for wording changed over time or they didn't review properly. I guess there's some question whether this should be "valid" or "well-formed". I wonder why they made language tags so complicated.

**Comment by annevk** [comment]
Kind of guarantees they'll just go unused the majority of the time.

**Comment by beverloo** [comment]
We can trivially determine whether a language tag is "well-formed" in Chrome. Determining whether it's "valid" is a bit more of a hassle. Previously we decided not to implement this because nobody else did, and the use-cases are not clear. Happy to follow suit if others decide to.

That said, note that we don't use `lang` and `dir` at all in Chrome.

**Comment by annevk** [comment]
So `lang` is effectively another data channel?

**Comment by beverloo** [comment]
Yes.

**Comment by annevk** [comment]
The "use case" was mostly so you could observe you did the correct thing with respect to setting the language. But I guess I don't care too strongly about it either way.

**Comment by aphillips** [comment]
Some comments on the above thread.

> I guess there's some question whether this should be "valid" or "well-formed".

The use of separate jargon is related to whether an implementation (tries to) keep a copy of the language subtag registry and validate whether all the subtags are "real" (valid) or if it just checks to see that the letters, digits, and hyphens match the appropriate pattern (well-formed). Having specific terminology lets us spell out what is required without saying all of that. Generally, because it *is* a hassle to validate the tag, the I18N WG recommends the term "well-formed".

> But as I mentioned earlier I wonder whether we still (or ever did) have agreement that 
> the requirement is a good, actually-useful one (rather than just a relic of what somebody
> thought was a good idea to add to the spec sometime, way back when).

The `lang` attribute (language metadata) has a real and visible effect in at least some browsers/user agents when it comes to font selection. When Chinese or Japanese text is rendered, the text is much more legible when a single font consistent with the content language is used (avoiding the so-called "ransom note effect"). This is only possible if language information is available.

There are other things that use the language of the text (in CSS, in text processing, in JS), but the above is the most common/visible use.

The `dir` attribute is very valuable, given that the Unicode Bidirectional Algorithm needs help from it and we spent ample effort on HTML5 and other specifications to get that right.

**Comment by annevk** [comment]
I guess since both CSS and HTML don't really have any requirements on language tags other than those coming forth from their own syntax restrictions we should indeed simply remove the requirement on user agents and maybe add it for authors. I'm leaning towards adding an encouragement for authors.

**Comment by aphillips** [comment]
Yes: although the more strict requirement of well formed would be nice to have, practically it is better for implementations to provide UI that produces the right result and specs mainly to apply the same (lesser) syntax restrictions consistently. Bad tags just don't work well.

**Comment by aphillips** [comment]
I'm not completely happy with the change though. I think there should be a SHOULD in the content string, even though that is not an implementation requirement: authors read these specs too and implementers should know not to just provide random strings as an option. 

Would this work?
--
 Its value is a string, which should consist of a BCP 47 language tag.
--

**Comment by annevk** [comment]
I try to avoid normative requirements on developers in API specifications. They can't really be enforced.

**Comment by aphillips** [comment]
I agree, but the current text makes no mention of what the value ought to be (well, obliquely, in the note, because there is a reference to [LANG], which is BCP47)--but it is a mere wisp of a suggestion. The notification.lang value is *intended* to be a BCP 47 language tag. We just don't require that implementations check it. 

The "should" would encourage implementers in the right direction. And we may find that later implementations are more rigorous than what we have now on what they emit. That would be a good thing, as it encourages interop.

**Comment by annevk** [comment]
You're right, [LANG] needs to be normative. Fixed.

**Comment by aphillips** [comment]
Thanks!
