### ISSUE TITLE
Use [SameObject] for Notification's vibrate attribute

### ISSUE THREAD

**Issue by foolip** [whatwg/notifications#66]
https://notifications.spec.whatwg.org/#api

```
[SameObject] readonly attribute FrozenArray<NotificationAction> actions;
```

Drop `[SameObject]`? Or, if it seems like a good idea, add it to the `vibrate` attribute too.

**Comment by annevk** [comment]
FrozenArray just means that the returned Array is frozen. So I guess we should add this annotation to `vibrate`.

**Comment by foolip** [comment]
Are you certain of that? If so, can you set me straight about it in https://github.com/w3c/webcomponents/issues/428 too? ;)

**Comment by annevk** [comment]
bz already noted "Anyway, having a FrozenArray attribute that changes at well-defined points (like whenever the current target changes, or event dispatch starts or ends) is quite feasible if we do want to go that route."

**Comment by foolip** [comment]
OK, I wasn't sure if it was feasible with the spec as-is or just stating that things could be easily changed to make it so. I think I've been confused about the main purpose of FrozenArray. It sounds like `[SameObject] readonly attribute T[] foo` would have fixed the `x.foo===x.foo` problems often mentioned, but that it would be possible to modify the array, which would be a bit weird.

So, this is great, it means that FrozenArray can be used to handle the cases in https://github.com/whatwg/html/issues/11 just fine.

**Comment by domenic** [comment]
In general [SameObject] and FrozenArray are orthogonal.

- [SameObject] FrozenArray means the property will always return the same frozen array (with the same values inside, since frozen arrays never change the values inside them)
- FrozenArray means that sometimes the property will return a different frozen array, usually changing at well-defined points. But again, in between changes the values inside the frozen array will not change.

`[SameObject] readonly attribute T[] foo` would indeed fix the `x.foo === x.foo` problems, but at the cost of using the annoying `T[]` type which is this kind of Frankenstein's array type that doesn't really match JavaScript arrays.
